baseURL = ""
languageCode = "en-gb"
title = "Hi, I'm Zoey!"
theme = "hello-friend-ng"

PygmentsCodeFences = true
PygmentsStyle = "fruity"

[markup.goldmark.renderer]
  unsafe = true

[author]
  name = "Zoey Sheffield"

[params]
  defaultTheme = "dark"
  
  [params.logo] 
    logoText     = "cd ~"
    logoHomeLink = "/"
  
  [[params.social]]
    name = "twitter"
    url  = "https://twitter.com/zoeyfyi/"

  [[params.social]]
    name = "facebook"
    url  = "https://www.facebook.com/zoeyfyi/"

  [[params.social]]
    name = "instagram"
    url  = "https://www.instagram.com/zoeyfyi/"

  [[params.social]]
    name = "steam"
    url  = "https://steamcommunity.com/id/zoeyfyi/"

  [[params.social]]
    name = "email"
    url  = "mailto:me@zoey.fyi"

  [[params.social]]
    name = "github"
    url  = "https://github.com/zoeyfyi/"

[menu]
  [[menu.main]]
    identifier = "posts"
    name       = "Posts"
    url        = "posts/"
